import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.servers": "Server list",
        "settings.servers.description": "Skip servers far out of view and remove the pills' GPU-layer hack.",
        "settings.members": "Member list",
        "settings.members.description": "Skip members far out of view. Discord already draws only the members near your screen, so this rarely saves anything.",
        "settings.margin": "Render distance (screens)",
        "settings.margin.description": "How many screen heights above and below stay fully rendered. Higher never shows an unrendered row even on very fast scrolls, lower saves more work.",
    },
    de: {
        "settings.servers": "Serverliste",
        "settings.servers.description": "Überspringt Server weit außerhalb des Sichtbereichs und entfernt den GPU-Ebenen-Trick der Pillen.",
        "settings.members": "Mitgliederliste",
        "settings.members.description": "Überspringt Mitglieder weit außerhalb des Sichtbereichs. Discord zeichnet ohnehin nur die Mitglieder in der Nähe deines Bildschirms, daher spart das selten etwas.",
        "settings.margin": "Renderdistanz (Bildschirme)",
        "settings.margin.description": "Wie viele Bildschirmhöhen darüber und darunter vollständig gerendert bleiben. Höher zeigt selbst bei sehr schnellem Scrollen nie eine ungerenderte Zeile, niedriger spart mehr Arbeit.",
    },
    es: {
        "settings.servers": "Lista de servidores",
        "settings.servers.description": "Omite los servidores muy fuera de la vista y quita el truco de capa GPU de las píldoras.",
        "settings.members": "Lista de miembros",
        "settings.members.description": "Omite los miembros muy fuera de la vista. Discord ya dibuja solo los miembros cerca de tu pantalla, así que rara vez ahorra algo.",
        "settings.margin": "Distancia de renderizado (pantallas)",
        "settings.margin.description": "Cuántas alturas de pantalla por encima y por debajo se mantienen totalmente renderizadas. Más alto nunca muestra una fila sin renderizar, ni siquiera al desplazarte muy rápido; más bajo ahorra más trabajo.",
    },
    fr: {
        "settings.servers": "Liste des serveurs",
        "settings.servers.description": "Ignore les serveurs très loin de la vue et supprime l'astuce de couche GPU des pastilles.",
        "settings.members": "Liste des membres",
        "settings.members.description": "Ignore les membres très loin de la vue. Discord n'affiche déjà que les membres proches de ton écran, donc cela économise rarement quelque chose.",
        "settings.margin": "Distance de rendu (écrans)",
        "settings.margin.description": "Combien de hauteurs d'écran au-dessus et en dessous restent entièrement rendues. Plus élevé, aucune ligne non rendue n'apparaît, même en défilant très vite ; plus bas, on économise plus de travail.",
    },
    ja: {
        "settings.servers": "サーバーリスト",
        "settings.servers.description": "画面から大きく外れたサーバーの描画を省き、ピルの GPU レイヤー対策を取り除きます。",
        "settings.members": "メンバーリスト",
        "settings.members.description": "画面から大きく外れたメンバーの描画を省きます。Discordはもともと画面付近のメンバーしか描画しないため、効果が出ることはほとんどありません。",
        "settings.margin": "描画範囲（画面数）",
        "settings.margin.description": "上下それぞれ、画面何枚分の高さを常にきちんと描画するかです。大きくすると、とても速くスクロールしても未描画の行が見えません。小さくすると、より多くの処理を節約できます。",
    },
    pl: {
        "settings.servers": "Lista serwerów",
        "settings.servers.description": "Pomija serwery daleko poza widokiem i usuwa sztuczkę z warstwą GPU dla wskaźników.",
        "settings.members": "Lista członków",
        "settings.members.description": "Pomija członków daleko poza widokiem. Discord i tak rysuje tylko członków blisko ekranu, więc rzadko cokolwiek to oszczędza.",
        "settings.margin": "Zasięg renderowania (ekrany)",
        "settings.margin.description": "Ile wysokości ekranu powyżej i poniżej pozostaje w pełni wyrenderowane. Wyższa wartość sprawia, że nawet przy bardzo szybkim przewijaniu nie zobaczysz niewyrenderowanego wiersza, niższa oszczędza więcej pracy.",
    },
    "pt-BR": {
        "settings.servers": "Lista de servidores",
        "settings.servers.description": "Pula servidores bem fora da tela e remove o truque de camada de GPU das pílulas.",
        "settings.members": "Lista de membros",
        "settings.members.description": "Pula membros bem fora da tela. O Discord já desenha só os membros perto da sua tela, então isso raramente economiza algo.",
        "settings.margin": "Distância de renderização (telas)",
        "settings.margin.description": "Quantas alturas de tela acima e abaixo continuam totalmente renderizadas. Mais alto nunca mostra uma linha sem renderizar, nem em rolagens muito rápidas; mais baixo economiza mais trabalho.",
    },
    ru: {
        "settings.servers": "Список серверов",
        "settings.servers.description": "Пропускает серверы далеко за пределами экрана и убирает хак GPU-слоя для индикаторов.",
        "settings.members": "Список участников",
        "settings.members.description": "Пропускает участников далеко за пределами экрана. Discord и так рисует только участников рядом с экраном, поэтому это редко что-то экономит.",
        "settings.margin": "Дальность отрисовки (экранов)",
        "settings.margin.description": "Сколько высот экрана выше и ниже остаётся полностью отрисованным. Чем больше, тем меньше шанс увидеть неотрисованную строку даже при очень быстрой прокрутке; чем меньше, тем больше экономия ресурсов.",
    },
    tr: {
        "settings.servers": "Sunucu listesi",
        "settings.servers.description": "Görüş alanının çok dışındaki sunucuları atlar ve rozetlerin GPU katmanı hilesini kaldırır.",
        "settings.members": "Üye listesi",
        "settings.members.description": "Görüş alanının çok dışındaki üyeleri atlar. Discord zaten yalnızca ekranına yakın üyeleri çizer, bu yüzden nadiren bir şey kazandırır.",
        "settings.margin": "Oluşturma mesafesi (ekran)",
        "settings.margin.description": "Üstte ve altta kaç ekran yüksekliğinin tamamen oluşturulmuş kalacağı. Yüksek değer çok hızlı kaydırmada bile oluşturulmamış satır göstermez, düşük değer daha çok işten tasarruf sağlar.",
    },
});
