import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.others": "Messages from others",
        "settings.others.description": "New messages from other people slide softly into the chat you have open.",
        "settings.own": "Your own messages",
        "settings.own.description": "Messages you send slide in the same way.",
        "settings.speed": "Motion",
        "settings.speed.description": "How far and how long new messages move. Discord's Reduce Motion setting turns it off either way.",
        "settings.speed.subtle": "Subtle",
        "settings.speed.normal": "Normal",
    },
    de: {
        "settings.others": "Nachrichten von anderen",
        "settings.others.description": "Neue Nachrichten von anderen gleiten sanft in den Chat, den du offen hast.",
        "settings.own": "Deine eigenen Nachrichten",
        "settings.own.description": "Nachrichten, die du sendest, gleiten genauso hinein.",
        "settings.speed": "Bewegung",
        "settings.speed.description": "Wie weit und wie lange sich neue Nachrichten bewegen. Discords Einstellung „Bewegungen reduzieren“ schaltet es in jedem Fall aus.",
        "settings.speed.subtle": "Dezent",
        "settings.speed.normal": "Normal",
    },
    es: {
        "settings.others": "Mensajes de otros",
        "settings.others.description": "Los mensajes nuevos de otras personas entran suavemente en el chat que tienes abierto.",
        "settings.own": "Tus propios mensajes",
        "settings.own.description": "Los mensajes que envías entran de la misma forma.",
        "settings.speed": "Movimiento",
        "settings.speed.description": "Cuánto y durante cuánto tiempo se mueven los mensajes nuevos. El ajuste Reducir movimiento de Discord lo desactiva en cualquier caso.",
        "settings.speed.subtle": "Sutil",
        "settings.speed.normal": "Normal",
    },
    fr: {
        "settings.others": "Messages des autres",
        "settings.others.description": "Les nouveaux messages des autres glissent en douceur dans le chat que tu as ouvert.",
        "settings.own": "Tes propres messages",
        "settings.own.description": "Les messages que tu envoies glissent de la même façon.",
        "settings.speed": "Mouvement",
        "settings.speed.description": "Jusqu'où et combien de temps les nouveaux messages bougent. Le réglage Réduire les animations de Discord le coupe dans tous les cas.",
        "settings.speed.subtle": "Discret",
        "settings.speed.normal": "Normal",
    },
    ja: {
        "settings.others": "ほかの人のメッセージ",
        "settings.others.description": "開いているチャットに、ほかの人の新しいメッセージがふわっと入ってきます。",
        "settings.own": "自分のメッセージ",
        "settings.own.description": "自分が送ったメッセージも同じように入ってきます。",
        "settings.speed": "動き",
        "settings.speed.description": "新しいメッセージが動く距離と時間です。Discord の「視差効果を減らす」がオンなら、どちらでも動きません。",
        "settings.speed.subtle": "控えめ",
        "settings.speed.normal": "ふつう",
    },
    pl: {
        "settings.others": "Wiadomości od innych",
        "settings.others.description": "Nowe wiadomości od innych łagodnie wsuwają się do otwartego czatu.",
        "settings.own": "Twoje wiadomości",
        "settings.own.description": "Wiadomości, które wysyłasz, wsuwają się tak samo.",
        "settings.speed": "Ruch",
        "settings.speed.description": "Jak daleko i jak długo przesuwają się nowe wiadomości. Ustawienie Ogranicz ruch w Discordzie i tak to wyłącza.",
        "settings.speed.subtle": "Delikatny",
        "settings.speed.normal": "Normalny",
    },
    "pt-BR": {
        "settings.others": "Mensagens dos outros",
        "settings.others.description": "Mensagens novas de outras pessoas entram suavemente no chat que você tem aberto.",
        "settings.own": "Suas próprias mensagens",
        "settings.own.description": "As mensagens que você envia entram do mesmo jeito.",
        "settings.speed": "Movimento",
        "settings.speed.description": "Quanto e por quanto tempo as mensagens novas se movem. A opção Reduzir movimento do Discord desliga isso de qualquer forma.",
        "settings.speed.subtle": "Sutil",
        "settings.speed.normal": "Normal",
    },
    ru: {
        "settings.others": "Сообщения других",
        "settings.others.description": "Новые сообщения других людей плавно появляются в открытом чате.",
        "settings.own": "Ваши сообщения",
        "settings.own.description": "Сообщения, которые вы отправляете, появляются так же.",
        "settings.speed": "Движение",
        "settings.speed.description": "Насколько далеко и как долго двигаются новые сообщения. Настройка Discord «Уменьшение движения» в любом случае это отключает.",
        "settings.speed.subtle": "Едва заметно",
        "settings.speed.normal": "Обычно",
    },
    tr: {
        "settings.others": "Başkalarının mesajları",
        "settings.others.description": "Başkalarından gelen yeni mesajlar açık olan sohbete yumuşakça kayarak girer.",
        "settings.own": "Kendi mesajların",
        "settings.own.description": "Gönderdiğin mesajlar da aynı şekilde kayarak girer.",
        "settings.speed": "Hareket",
        "settings.speed.description": "Yeni mesajların ne kadar uzağa ve ne kadar süre hareket ettiği. Discord'un Hareketi azalt ayarı her durumda bunu kapatır.",
        "settings.speed.subtle": "Hafif",
        "settings.speed.normal": "Normal",
    },
});
