import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "menu.mute": "Mute",
        "menu.deafen": "Deafen",
        "menu.status": "Status",
        "menu.online": "Online",
        "menu.idle": "Idle",
        "menu.dnd": "Do Not Disturb",
        "menu.invisible": "Invisible",
        "menu.recent": "Recent DMs",
        "settings.voice": "Mute and Deafen",
        "settings.voice.description": "Shown while you're not in a call. In one, Discord's own are already there.",
        "settings.status": "Status",
        "settings.status.description": "Go Online, Idle, Do Not Disturb or Invisible from the tray.",
        "settings.recent": "Recent DMs",
        "settings.recent.description": "Your latest DMs and group chats. Clicking one opens Discord on it.",
        "settings.recentCount": "How many recent DMs",
        "toast.statusFailed": "Couldn't change your status",
    },
    de: {
        "menu.mute": "Stummschalten",
        "menu.deafen": "Ton aus",
        "menu.status": "Status",
        "menu.online": "Online",
        "menu.idle": "Abwesend",
        "menu.dnd": "Bitte nicht stören",
        "menu.invisible": "Unsichtbar",
        "menu.recent": "Letzte Direktnachrichten",
        "settings.voice": "Stummschalten und Ton aus",
        "settings.voice.description": "Wird angezeigt, solange du in keinem Anruf bist. In einem Anruf sind Discords eigene schon da.",
        "settings.status": "Status",
        "settings.status.description": "Online, Abwesend, Bitte nicht stören oder Unsichtbar direkt aus dem Infobereich.",
        "settings.recent": "Letzte Direktnachrichten",
        "settings.recent.description": "Deine neuesten Direktnachrichten und Gruppenchats. Ein Klick öffnet Discord dort.",
        "settings.recentCount": "Wie viele Direktnachrichten",
        "toast.statusFailed": "Dein Status konnte nicht geändert werden",
    },
    es: {
        "menu.mute": "Silenciar",
        "menu.deafen": "Ensordecer",
        "menu.status": "Estado",
        "menu.online": "En línea",
        "menu.idle": "Ausente",
        "menu.dnd": "No molestar",
        "menu.invisible": "Invisible",
        "menu.recent": "Mensajes directos recientes",
        "settings.voice": "Silenciar y Ensordecer",
        "settings.voice.description": "Se muestran mientras no estás en una llamada. En una, ya están los de Discord.",
        "settings.status": "Estado",
        "settings.status.description": "Ponte En línea, Ausente, No molestar o Invisible desde la bandeja.",
        "settings.recent": "Mensajes directos recientes",
        "settings.recent.description": "Tus últimos mensajes directos y chats de grupo. Al hacer clic en uno, Discord se abre ahí.",
        "settings.recentCount": "Cuántos mensajes directos",
        "toast.statusFailed": "No se pudo cambiar tu estado",
    },
    fr: {
        "menu.mute": "Rendre muet",
        "menu.deafen": "Mettre en sourdine",
        "menu.status": "Statut",
        "menu.online": "En ligne",
        "menu.idle": "Inactif",
        "menu.dnd": "Ne pas déranger",
        "menu.invisible": "Invisible",
        "menu.recent": "MP récents",
        "settings.voice": "Rendre muet et Mettre en sourdine",
        "settings.voice.description": "Affichés quand tu n'es pas en appel. Pendant un appel, ceux de Discord sont déjà là.",
        "settings.status": "Statut",
        "settings.status.description": "Passe En ligne, Inactif, Ne pas déranger ou Invisible depuis la zone de notification.",
        "settings.recent": "MP récents",
        "settings.recent.description": "Tes derniers MP et groupes. Un clic ouvre Discord dessus.",
        "settings.recentCount": "Combien de MP récents",
        "toast.statusFailed": "Impossible de changer ton statut",
    },
    ja: {
        "menu.mute": "ミュート",
        "menu.deafen": "スピーカーミュート",
        "menu.status": "ステータス",
        "menu.online": "オンライン",
        "menu.idle": "退席中",
        "menu.dnd": "取り込み中",
        "menu.invisible": "オンライン状態を隠す",
        "menu.recent": "最近のDM",
        "settings.voice": "ミュートとスピーカーミュート",
        "settings.voice.description": "通話中でないときに表示されます。通話中は Discord 自身の項目があります。",
        "settings.status": "ステータス",
        "settings.status.description": "タスクトレイからオンライン、退席中、取り込み中、オンライン状態を隠すに切り替えます。",
        "settings.recent": "最近のDM",
        "settings.recent.description": "最近のDMとグループチャット。クリックすると Discord でそこを開きます。",
        "settings.recentCount": "表示するDMの数",
        "toast.statusFailed": "ステータスを変更できませんでした",
    },
    pl: {
        "menu.mute": "Wycisz",
        "menu.deafen": "Wyłącz dźwięk",
        "menu.status": "Status",
        "menu.online": "Dostępny",
        "menu.idle": "Zaraz wracam",
        "menu.dnd": "Nie przeszkadzać",
        "menu.invisible": "Niewidoczny",
        "menu.recent": "Ostatnie wiadomości prywatne",
        "settings.voice": "Wycisz i Wyłącz dźwięk",
        "settings.voice.description": "Widoczne, gdy nie jesteś w rozmowie. W rozmowie są już te od Discorda.",
        "settings.status": "Status",
        "settings.status.description": "Ustaw Dostępny, Zaraz wracam, Nie przeszkadzać albo Niewidoczny z zasobnika.",
        "settings.recent": "Ostatnie wiadomości prywatne",
        "settings.recent.description": "Twoje najnowsze wiadomości prywatne i czaty grupowe. Kliknięcie otwiera tam Discorda.",
        "settings.recentCount": "Ile wiadomości prywatnych",
        "toast.statusFailed": "Nie udało się zmienić statusu",
    },
    "pt-BR": {
        "menu.mute": "Silenciar",
        "menu.deafen": "Ensurdecer",
        "menu.status": "Status",
        "menu.online": "Disponível",
        "menu.idle": "Ausente",
        "menu.dnd": "Não perturbar",
        "menu.invisible": "Invisível",
        "menu.recent": "Mensagens diretas recentes",
        "settings.voice": "Silenciar e Ensurdecer",
        "settings.voice.description": "Aparecem quando você não está em uma chamada. Em uma, os do próprio Discord já estão lá.",
        "settings.status": "Status",
        "settings.status.description": "Fique Disponível, Ausente, Não perturbar ou Invisível pela bandeja.",
        "settings.recent": "Mensagens diretas recentes",
        "settings.recent.description": "Suas mensagens diretas e grupos mais recentes. Clicar em um abre o Discord nele.",
        "settings.recentCount": "Quantas mensagens diretas",
        "toast.statusFailed": "Não foi possível mudar seu status",
    },
    ru: {
        "menu.mute": "Выключить микрофон",
        "menu.deafen": "Выключить звук",
        "menu.status": "Статус",
        "menu.online": "В сети",
        "menu.idle": "Неактивен",
        "menu.dnd": "Не беспокоить",
        "menu.invisible": "Невидимый",
        "menu.recent": "Недавние личные сообщения",
        "settings.voice": "Микрофон и звук",
        "settings.voice.description": "Видны, пока вы не в звонке. В звонке там уже есть пункты самого Discord.",
        "settings.status": "Статус",
        "settings.status.description": "В сети, Неактивен, Не беспокоить или Невидимый прямо из трея.",
        "settings.recent": "Недавние личные сообщения",
        "settings.recent.description": "Ваши последние личные сообщения и группы. Клик открывает Discord на них.",
        "settings.recentCount": "Сколько личных сообщений",
        "toast.statusFailed": "Не удалось изменить статус",
    },
    tr: {
        "menu.mute": "Sustur",
        "menu.deafen": "Sağırlaştır",
        "menu.status": "Durum",
        "menu.online": "Çevrimiçi",
        "menu.idle": "Boşta",
        "menu.dnd": "Rahatsız Etmeyin",
        "menu.invisible": "Görünmez",
        "menu.recent": "Son özel mesajlar",
        "settings.voice": "Sustur ve Sağırlaştır",
        "settings.voice.description": "Bir aramada değilken görünür. Aramadayken Discord'un kendi seçenekleri zaten oradadır.",
        "settings.status": "Durum",
        "settings.status.description": "Sistem tepsisinden Çevrimiçi, Boşta, Rahatsız Etmeyin veya Görünmez ol.",
        "settings.recent": "Son özel mesajlar",
        "settings.recent.description": "En son özel mesajların ve grup sohbetlerin. Birine tıklamak Discord'u orada açar.",
        "settings.recentCount": "Kaç özel mesaj",
        "toast.statusFailed": "Durumun değiştirilemedi",
    },
});
