import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "boot.checking": "checking for updates",
        "boot.downloading": "downloading update {current} of {total}",
        "boot.installing": "installing update {current} of {total}",
        "boot.updateFailed": "update failed",
        "boot.retrying": "retrying in {seconds}s",
        "boot.upToDate": "up to date",
        "boot.updated": "updates installed",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "theme",
        "boot.safeMode": "safe mode",
        "boot.pluginsOff": "plugins off",
        "boot.plugins": "plugins",
        "boot.count": "{done} of {total}",
        "boot.opening": "opening discord",
        "settings.showPlugins": "List each plugin",
        "settings.showPlugins.description": "Every plugin gets its own line as it starts. Off: one line with the count.",
        "settings.accent": "Accent",
        "settings.accent.description": "The colour of the current line's arrow and the progress bar.",
        "accent.white": "White",
        "accent.green": "Green",
        "accent.blue": "Blue",
        "accent.amber": "Amber",
        "accent.pink": "Pink",
        "settings.compact": "Compact",
        "settings.compact.description": "A smaller window with smaller text.",
        "preview": "Preview",
        "preview.hint": "Plays a made-up start with your plugins. The real one shows the next time Discord starts.",
        "preview.failed": "Couldn't open the preview",
    },
    de: {
        "boot.checking": "suche nach updates",
        "boot.downloading": "lade update {current} von {total}",
        "boot.installing": "installiere update {current} von {total}",
        "boot.updateFailed": "update fehlgeschlagen",
        "boot.retrying": "neuer versuch in {seconds} s",
        "boot.upToDate": "aktuell",
        "boot.updated": "updates installiert",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "theme",
        "boot.safeMode": "abgesicherter modus",
        "boot.pluginsOff": "plugins aus",
        "boot.plugins": "plugins",
        "boot.count": "{done} von {total}",
        "boot.opening": "öffne discord",
        "settings.showPlugins": "Jedes Plugin auflisten",
        "settings.showPlugins.description": "Jedes Plugin bekommt beim Start eine eigene Zeile. Aus: eine Zeile mit der Anzahl.",
        "settings.accent": "Akzent",
        "settings.accent.description": "Die Farbe des Pfeils in der aktuellen Zeile und des Fortschrittsbalkens.",
        "accent.white": "Weiß",
        "accent.green": "Grün",
        "accent.blue": "Blau",
        "accent.amber": "Bernstein",
        "accent.pink": "Rosa",
        "settings.compact": "Kompakt",
        "settings.compact.description": "Ein kleineres Fenster mit kleinerer Schrift.",
        "preview": "Vorschau",
        "preview.hint": "Spielt einen ausgedachten Start mit deinen Plugins ab. Den echten siehst du beim nächsten Start von Discord.",
        "preview.failed": "Die Vorschau konnte nicht geöffnet werden",
    },
    es: {
        "boot.checking": "buscando actualizaciones",
        "boot.downloading": "descargando actualización {current} de {total}",
        "boot.installing": "instalando actualización {current} de {total}",
        "boot.updateFailed": "falló la actualización",
        "boot.retrying": "reintento en {seconds} s",
        "boot.upToDate": "al día",
        "boot.updated": "actualizaciones instaladas",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "tema",
        "boot.safeMode": "modo seguro",
        "boot.pluginsOff": "plugins apagados",
        "boot.plugins": "plugins",
        "boot.count": "{done} de {total}",
        "boot.opening": "abriendo discord",
        "settings.showPlugins": "Mostrar cada plugin",
        "settings.showPlugins.description": "Cada plugin tiene su propia línea al iniciarse. Desactivado: una línea con la cuenta.",
        "settings.accent": "Acento",
        "settings.accent.description": "El color de la flecha de la línea actual y de la barra de progreso.",
        "accent.white": "Blanco",
        "accent.green": "Verde",
        "accent.blue": "Azul",
        "accent.amber": "Ámbar",
        "accent.pink": "Rosa",
        "settings.compact": "Compacto",
        "settings.compact.description": "Una ventana más pequeña con letra más pequeña.",
        "preview": "Vista previa",
        "preview.hint": "Reproduce un inicio inventado con tus plugins. El de verdad se ve la próxima vez que Discord se inicie.",
        "preview.failed": "No se pudo abrir la vista previa",
    },
    fr: {
        "boot.checking": "recherche de mises à jour",
        "boot.downloading": "téléchargement de la mise à jour {current} sur {total}",
        "boot.installing": "installation de la mise à jour {current} sur {total}",
        "boot.updateFailed": "échec de la mise à jour",
        "boot.retrying": "nouvel essai dans {seconds} s",
        "boot.upToDate": "à jour",
        "boot.updated": "mises à jour installées",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "thème",
        "boot.safeMode": "mode sans échec",
        "boot.pluginsOff": "plugins désactivés",
        "boot.plugins": "plugins",
        "boot.count": "{done} sur {total}",
        "boot.opening": "ouverture de discord",
        "settings.showPlugins": "Lister chaque plugin",
        "settings.showPlugins.description": "Chaque plugin a sa propre ligne quand il démarre. Désactivé : une ligne avec le compte.",
        "settings.accent": "Accent",
        "settings.accent.description": "La couleur de la flèche de la ligne en cours et de la barre de progression.",
        "accent.white": "Blanc",
        "accent.green": "Vert",
        "accent.blue": "Bleu",
        "accent.amber": "Ambre",
        "accent.pink": "Rose",
        "settings.compact": "Compact",
        "settings.compact.description": "Une fenêtre plus petite avec un texte plus petit.",
        "preview": "Aperçu",
        "preview.hint": "Joue un démarrage inventé avec tes plugins. Le vrai s'affiche au prochain démarrage de Discord.",
        "preview.failed": "Impossible d'ouvrir l'aperçu",
    },
    ja: {
        "boot.checking": "アップデートを確認中",
        "boot.downloading": "アップデートをダウンロード中 {current}/{total}",
        "boot.installing": "アップデートをインストール中 {current}/{total}",
        "boot.updateFailed": "アップデート失敗",
        "boot.retrying": "{seconds} 秒後に再試行",
        "boot.upToDate": "最新",
        "boot.updated": "アップデート済み",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "テーマ",
        "boot.safeMode": "セーフモード",
        "boot.pluginsOff": "プラグインはオフ",
        "boot.plugins": "プラグイン",
        "boot.count": "{done}/{total}",
        "boot.opening": "discord を開いています",
        "settings.showPlugins": "プラグインを 1 行ずつ表示",
        "settings.showPlugins.description": "起動したプラグインがそれぞれ 1 行で表示されます。オフにすると件数だけの 1 行になります。",
        "settings.accent": "アクセント",
        "settings.accent.description": "現在の行の矢印と進行バーの色です。",
        "accent.white": "白",
        "accent.green": "緑",
        "accent.blue": "青",
        "accent.amber": "琥珀",
        "accent.pink": "ピンク",
        "settings.compact": "コンパクト",
        "settings.compact.description": "小さめのウィンドウと文字。",
        "preview": "プレビュー",
        "preview.hint": "あなたのプラグインで架空の起動を再生します。本物は次に Discord を起動したときに表示されます。",
        "preview.failed": "プレビューを開けませんでした",
    },
    pl: {
        "boot.checking": "szukam aktualizacji",
        "boot.downloading": "pobieram aktualizację {current} z {total}",
        "boot.installing": "instaluję aktualizację {current} z {total}",
        "boot.updateFailed": "aktualizacja nieudana",
        "boot.retrying": "ponowna próba za {seconds} s",
        "boot.upToDate": "aktualny",
        "boot.updated": "zainstalowane aktualizacje",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "motyw",
        "boot.safeMode": "tryb awaryjny",
        "boot.pluginsOff": "pluginy wyłączone",
        "boot.plugins": "pluginy",
        "boot.count": "{done} z {total}",
        "boot.opening": "otwieram discorda",
        "settings.showPlugins": "Pokazuj każdy plugin",
        "settings.showPlugins.description": "Każdy plugin dostaje własną linijkę, gdy startuje. Wyłączone: jedna linijka z liczbą.",
        "settings.accent": "Akcent",
        "settings.accent.description": "Kolor strzałki w bieżącej linijce i paska postępu.",
        "accent.white": "Biały",
        "accent.green": "Zielony",
        "accent.blue": "Niebieski",
        "accent.amber": "Bursztynowy",
        "accent.pink": "Różowy",
        "settings.compact": "Kompaktowy",
        "settings.compact.description": "Mniejsze okno i mniejszy tekst.",
        "preview": "Podgląd",
        "preview.hint": "Odtwarza zmyślony start z twoimi pluginami. Prawdziwy zobaczysz przy następnym uruchomieniu Discorda.",
        "preview.failed": "Nie udało się otworzyć podglądu",
    },
    "pt-BR": {
        "boot.checking": "procurando atualizações",
        "boot.downloading": "baixando atualização {current} de {total}",
        "boot.installing": "instalando atualização {current} de {total}",
        "boot.updateFailed": "a atualização falhou",
        "boot.retrying": "tentando de novo em {seconds} s",
        "boot.upToDate": "atualizado",
        "boot.updated": "atualizações instaladas",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "tema",
        "boot.safeMode": "modo seguro",
        "boot.pluginsOff": "plugins desligados",
        "boot.plugins": "plugins",
        "boot.count": "{done} de {total}",
        "boot.opening": "abrindo o discord",
        "settings.showPlugins": "Listar cada plugin",
        "settings.showPlugins.description": "Cada plugin ganha a sua própria linha quando inicia. Desligado: uma linha com a contagem.",
        "settings.accent": "Destaque",
        "settings.accent.description": "A cor da seta da linha atual e da barra de progresso.",
        "accent.white": "Branco",
        "accent.green": "Verde",
        "accent.blue": "Azul",
        "accent.amber": "Âmbar",
        "accent.pink": "Rosa",
        "settings.compact": "Compacto",
        "settings.compact.description": "Uma janela menor com texto menor.",
        "preview": "Pré-visualizar",
        "preview.hint": "Mostra um início de mentirinha com os seus plugins. O de verdade aparece na próxima vez que o Discord iniciar.",
        "preview.failed": "Não foi possível abrir a pré-visualização",
    },
    ru: {
        "boot.checking": "проверка обновлений",
        "boot.downloading": "загрузка обновления {current} из {total}",
        "boot.installing": "установка обновления {current} из {total}",
        "boot.updateFailed": "обновление не удалось",
        "boot.retrying": "повтор через {seconds} с",
        "boot.upToDate": "всё обновлено",
        "boot.updated": "обновления установлены",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "тема",
        "boot.safeMode": "безопасный режим",
        "boot.pluginsOff": "плагины выключены",
        "boot.plugins": "плагины",
        "boot.count": "{done} из {total}",
        "boot.opening": "открываем discord",
        "settings.showPlugins": "Показывать каждый плагин",
        "settings.showPlugins.description": "Каждый плагин получает свою строку, когда запускается. Если выключено: одна строка со счётчиком.",
        "settings.accent": "Акцент",
        "settings.accent.description": "Цвет стрелки в текущей строке и полоски прогресса.",
        "accent.white": "Белый",
        "accent.green": "Зелёный",
        "accent.blue": "Синий",
        "accent.amber": "Янтарный",
        "accent.pink": "Розовый",
        "settings.compact": "Компактно",
        "settings.compact.description": "Окно и текст поменьше.",
        "preview": "Предпросмотр",
        "preview.hint": "Показывает выдуманный запуск с вашими плагинами. Настоящий появится при следующем запуске Discord.",
        "preview.failed": "Не удалось открыть предпросмотр",
    },
    tr: {
        "boot.checking": "güncellemeler denetleniyor",
        "boot.downloading": "güncelleme indiriliyor {current}/{total}",
        "boot.installing": "güncelleme kuruluyor {current}/{total}",
        "boot.updateFailed": "güncelleme başarısız",
        "boot.retrying": "{seconds} sn sonra yeniden denenecek",
        "boot.upToDate": "güncel",
        "boot.updated": "güncellemeler kuruldu",
        "boot.discord": "discord",
        "boot.evi": "evi",
        "boot.theme": "tema",
        "boot.safeMode": "güvenli mod",
        "boot.pluginsOff": "eklentiler kapalı",
        "boot.plugins": "eklentiler",
        "boot.count": "{done}/{total}",
        "boot.opening": "discord açılıyor",
        "settings.showPlugins": "Her eklentiyi listele",
        "settings.showPlugins.description": "Her eklenti başlarken kendi satırını alır. Kapalıyken: sayıyı gösteren tek satır.",
        "settings.accent": "Vurgu",
        "settings.accent.description": "Geçerli satırdaki okun ve ilerleme çubuğunun rengi.",
        "accent.white": "Beyaz",
        "accent.green": "Yeşil",
        "accent.blue": "Mavi",
        "accent.amber": "Kehribar",
        "accent.pink": "Pembe",
        "settings.compact": "Kompakt",
        "settings.compact.description": "Daha küçük bir pencere ve daha küçük yazı.",
        "preview": "Önizleme",
        "preview.hint": "Eklentilerinle uydurma bir açılış oynatır. Gerçeğini Discord bir sonraki açılışında görürsün.",
        "preview.failed": "Önizleme açılamadı",
    },
});
