import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.corner": "Corner",
        "settings.corner.description": "Where on your screen notifications appear.",
        "corner.bottomRight": "Bottom right",
        "corner.bottomLeft": "Bottom left",
        "corner.topRight": "Top right",
        "corner.topLeft": "Top left",
        "settings.screen": "Screen",
        "settings.screen.description": "With more than one monitor, which one shows them.",
        "screen.discord": "The screen Discord is on",
        "screen.primary": "Your main screen",
        "screen.cursor": "The screen your mouse is on",
        "settings.duration": "Seconds on screen",
        "settings.duration.description": "Hovering a notification keeps it there.",
        "settings.maxVisible": "At most on screen",
        "settings.maxVisible.description": "Older ones make room for new ones.",
        "settings.showText": "Show message text",
        "settings.showText.description": "Turn it off to only show who it's from, for when others can see your screen.",
        "settings.reply": "Reply from the notification",
        "settings.reply.description": "A Reply button that sends a real reply without opening Discord.",
        "settings.others": "Other notifications too",
        "settings.others.description": "Friend requests and everything else Discord tells you about, in the same style.",
        "settings.overFullscreen": "Show over fullscreen apps",
        "settings.overFullscreen.description": "Discord holds notifications back while a fullscreen game or Focus assist is on. Turn this on to show them anyway.",
        "panel.test": "Show a test notification",
        "panel.testFailed": "Couldn't open the notification window. Restart Discord and try again.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "This is how your notifications look now. Hover to keep it on screen, click to open Discord.",
        "label.open": "Open in Discord",
        "label.close": "Close",
        "label.reply": "Reply",
        "label.placeholder": "Reply to {name}",
        "label.send": "Send reply",
        "label.sending": "Sending…",
        "label.sent": "Reply sent",
        "label.failed": "Couldn't send. Press Enter to try again.",
        "context.dm": "Direct message",
        "context.group": "Group DM",
        "body.hidden": "New message",
        "body.attachment": "Sent an attachment",
    },
    de: {
        "settings.corner": "Ecke",
        "settings.corner.description": "Wo auf deinem Bildschirm Benachrichtigungen erscheinen.",
        "corner.bottomRight": "Unten rechts",
        "corner.bottomLeft": "Unten links",
        "corner.topRight": "Oben rechts",
        "corner.topLeft": "Oben links",
        "settings.screen": "Bildschirm",
        "settings.screen.description": "Bei mehreren Monitoren: auf welchem sie erscheinen.",
        "screen.discord": "Der Bildschirm mit Discord",
        "screen.primary": "Dein Hauptbildschirm",
        "screen.cursor": "Der Bildschirm mit deiner Maus",
        "settings.duration": "Sekunden auf dem Bildschirm",
        "settings.duration.description": "Fährst du mit der Maus darüber, bleibt die Benachrichtigung stehen.",
        "settings.maxVisible": "Höchstens gleichzeitig",
        "settings.maxVisible.description": "Ältere machen Platz für neue.",
        "settings.showText": "Nachrichtentext anzeigen",
        "settings.showText.description": "Aus: Es steht nur da, von wem sie ist, falls andere deinen Bildschirm sehen.",
        "settings.reply": "Aus der Benachrichtigung antworten",
        "settings.reply.description": "Ein Antworten-Button, der eine echte Antwort sendet, ohne Discord zu öffnen.",
        "settings.others": "Auch andere Benachrichtigungen",
        "settings.others.description": "Freundschaftsanfragen und alles andere, worüber Discord dich informiert, im selben Stil.",
        "settings.overFullscreen": "Über Vollbild-Apps anzeigen",
        "settings.overFullscreen.description": "Discord hält Benachrichtigungen zurück, solange ein Spiel im Vollbild oder der Fokus-Assistent läuft. Schalte das ein, um sie trotzdem zu zeigen.",
        "panel.test": "Testbenachrichtigung zeigen",
        "panel.testFailed": "Das Benachrichtigungsfenster ließ sich nicht öffnen. Starte Discord neu und versuch es noch einmal.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "So sehen deine Benachrichtigungen jetzt aus. Mit der Maus darüber bleibt sie stehen, ein Klick öffnet Discord.",
        "label.open": "In Discord öffnen",
        "label.close": "Schließen",
        "label.reply": "Antworten",
        "label.placeholder": "{name} antworten",
        "label.send": "Antwort senden",
        "label.sending": "Wird gesendet …",
        "label.sent": "Antwort gesendet",
        "label.failed": "Senden fehlgeschlagen. Drück Enter, um es noch einmal zu versuchen.",
        "context.dm": "Direktnachricht",
        "context.group": "Gruppen-DM",
        "body.hidden": "Neue Nachricht",
        "body.attachment": "Hat einen Anhang gesendet",
    },
    es: {
        "settings.corner": "Esquina",
        "settings.corner.description": "En qué parte de la pantalla aparecen las notificaciones.",
        "corner.bottomRight": "Abajo a la derecha",
        "corner.bottomLeft": "Abajo a la izquierda",
        "corner.topRight": "Arriba a la derecha",
        "corner.topLeft": "Arriba a la izquierda",
        "settings.screen": "Pantalla",
        "settings.screen.description": "Si tienes más de un monitor, en cuál aparecen.",
        "screen.discord": "La pantalla donde está Discord",
        "screen.primary": "Tu pantalla principal",
        "screen.cursor": "La pantalla donde está el ratón",
        "settings.duration": "Segundos en pantalla",
        "settings.duration.description": "Si pasas el ratón por encima, se queda.",
        "settings.maxVisible": "Como máximo en pantalla",
        "settings.maxVisible.description": "Las más antiguas dejan sitio a las nuevas.",
        "settings.showText": "Mostrar el texto del mensaje",
        "settings.showText.description": "Desactívalo para mostrar solo de quién es, por si otros ven tu pantalla.",
        "settings.reply": "Responder desde la notificación",
        "settings.reply.description": "Un botón Responder que envía una respuesta de verdad sin abrir Discord.",
        "settings.others": "También otras notificaciones",
        "settings.others.description": "Solicitudes de amistad y todo lo demás que te avisa Discord, con el mismo estilo.",
        "settings.overFullscreen": "Mostrar sobre apps a pantalla completa",
        "settings.overFullscreen.description": "Discord retiene las notificaciones mientras hay un juego a pantalla completa o el Asistente de concentración activado. Actívalo para mostrarlas igualmente.",
        "panel.test": "Mostrar una notificación de prueba",
        "panel.testFailed": "No se pudo abrir la ventana de notificaciones. Reinicia Discord y vuelve a intentarlo.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "Así se ven ahora tus notificaciones. Pasa el ratón para que se quede y haz clic para abrir Discord.",
        "label.open": "Abrir en Discord",
        "label.close": "Cerrar",
        "label.reply": "Responder",
        "label.placeholder": "Responder a {name}",
        "label.send": "Enviar respuesta",
        "label.sending": "Enviando…",
        "label.sent": "Respuesta enviada",
        "label.failed": "No se pudo enviar. Pulsa Intro para volver a intentarlo.",
        "context.dm": "Mensaje directo",
        "context.group": "MD grupal",
        "body.hidden": "Mensaje nuevo",
        "body.attachment": "Envió un archivo adjunto",
    },
    fr: {
        "settings.corner": "Coin",
        "settings.corner.description": "Où les notifications apparaissent sur ton écran.",
        "corner.bottomRight": "En bas à droite",
        "corner.bottomLeft": "En bas à gauche",
        "corner.topRight": "En haut à droite",
        "corner.topLeft": "En haut à gauche",
        "settings.screen": "Écran",
        "settings.screen.description": "Avec plusieurs moniteurs, celui qui les affiche.",
        "screen.discord": "L'écran où se trouve Discord",
        "screen.primary": "Ton écran principal",
        "screen.cursor": "L'écran où se trouve ta souris",
        "settings.duration": "Secondes à l'écran",
        "settings.duration.description": "Passer la souris dessus la garde affichée.",
        "settings.maxVisible": "Au maximum à l'écran",
        "settings.maxVisible.description": "Les plus anciennes laissent la place aux nouvelles.",
        "settings.showText": "Afficher le texte du message",
        "settings.showText.description": "Désactive-le pour n'afficher que l'expéditeur, quand d'autres peuvent voir ton écran.",
        "settings.reply": "Répondre depuis la notification",
        "settings.reply.description": "Un bouton Répondre qui envoie une vraie réponse sans ouvrir Discord.",
        "settings.others": "Les autres notifications aussi",
        "settings.others.description": "Demandes d'ami et tout ce que Discord te signale d'autre, dans le même style.",
        "settings.overFullscreen": "Afficher par-dessus les applis en plein écran",
        "settings.overFullscreen.description": "Discord retient les notifications pendant un jeu en plein écran ou quand l'Assistant de concentration est activé. Active ceci pour les afficher quand même.",
        "panel.test": "Afficher une notification de test",
        "panel.testFailed": "Impossible d'ouvrir la fenêtre des notifications. Redémarre Discord et réessaie.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "Voici à quoi ressemblent maintenant tes notifications. Survole-la pour la garder, clique pour ouvrir Discord.",
        "label.open": "Ouvrir dans Discord",
        "label.close": "Fermer",
        "label.reply": "Répondre",
        "label.placeholder": "Répondre à {name}",
        "label.send": "Envoyer la réponse",
        "label.sending": "Envoi…",
        "label.sent": "Réponse envoyée",
        "label.failed": "Échec de l'envoi. Appuie sur Entrée pour réessayer.",
        "context.dm": "Message privé",
        "context.group": "MP de groupe",
        "body.hidden": "Nouveau message",
        "body.attachment": "A envoyé une pièce jointe",
    },
    ja: {
        "settings.corner": "表示位置",
        "settings.corner.description": "通知が画面のどこに出るか。",
        "corner.bottomRight": "右下",
        "corner.bottomLeft": "左下",
        "corner.topRight": "右上",
        "corner.topLeft": "左上",
        "settings.screen": "画面",
        "settings.screen.description": "モニターが複数あるとき、どの画面に出すか。",
        "screen.discord": "Discord がある画面",
        "screen.primary": "メインの画面",
        "screen.cursor": "マウスがある画面",
        "settings.duration": "表示する秒数",
        "settings.duration.description": "マウスを乗せている間は消えません。",
        "settings.maxVisible": "同時に表示する最大数",
        "settings.maxVisible.description": "古いものから新しいものに場所を譲ります。",
        "settings.showText": "メッセージ本文を表示",
        "settings.showText.description": "オフにすると送信者だけを表示します。画面を見られるときに。",
        "settings.reply": "通知から返信",
        "settings.reply.description": "Discord を開かずに本物の返信を送れる返信ボタン。",
        "settings.others": "ほかの通知も",
        "settings.others.description": "フレンド申請など、Discord が知らせるほかの通知も同じスタイルで。",
        "settings.overFullscreen": "全画面アプリの上にも表示",
        "settings.overFullscreen.description": "全画面のゲームや集中モードの間、Discord は通知を控えます。オンにするとそれでも表示します。",
        "panel.test": "テスト通知を表示",
        "panel.testFailed": "通知ウィンドウを開けませんでした。Discord を再起動してもう一度お試しください。",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "通知はこんな見た目になりました。マウスを乗せると残り、クリックすると Discord が開きます。",
        "label.open": "Discord で開く",
        "label.close": "閉じる",
        "label.reply": "返信",
        "label.placeholder": "{name} に返信",
        "label.send": "返信を送信",
        "label.sending": "送信中…",
        "label.sent": "返信しました",
        "label.failed": "送信できませんでした。Enter でもう一度試せます。",
        "context.dm": "ダイレクトメッセージ",
        "context.group": "グループ DM",
        "body.hidden": "新しいメッセージ",
        "body.attachment": "添付ファイルを送信しました",
    },
    pl: {
        "settings.corner": "Róg",
        "settings.corner.description": "Gdzie na ekranie pojawiają się powiadomienia.",
        "corner.bottomRight": "Prawy dolny",
        "corner.bottomLeft": "Lewy dolny",
        "corner.topRight": "Prawy górny",
        "corner.topLeft": "Lewy górny",
        "settings.screen": "Ekran",
        "settings.screen.description": "Przy kilku monitorach: na którym się pojawiają.",
        "screen.discord": "Ekran, na którym jest Discord",
        "screen.primary": "Twój główny ekran",
        "screen.cursor": "Ekran, na którym jest mysz",
        "settings.duration": "Sekundy na ekranie",
        "settings.duration.description": "Najechanie myszą zatrzymuje powiadomienie.",
        "settings.maxVisible": "Najwyżej na ekranie",
        "settings.maxVisible.description": "Starsze robią miejsce nowym.",
        "settings.showText": "Pokazuj treść wiadomości",
        "settings.showText.description": "Wyłącz, aby pokazywać tylko nadawcę, gdy inni widzą twój ekran.",
        "settings.reply": "Odpowiadanie z powiadomienia",
        "settings.reply.description": "Przycisk Odpowiedz, który wysyła prawdziwą odpowiedź bez otwierania Discorda.",
        "settings.others": "Także inne powiadomienia",
        "settings.others.description": "Zaproszenia do znajomych i wszystko inne, o czym informuje Discord, w tym samym stylu.",
        "settings.overFullscreen": "Pokazuj nad aplikacjami pełnoekranowymi",
        "settings.overFullscreen.description": "Discord wstrzymuje powiadomienia podczas gry na pełnym ekranie lub gdy włączone jest Wspomaganie koncentracji. Włącz, aby i tak je pokazywać.",
        "panel.test": "Pokaż testowe powiadomienie",
        "panel.testFailed": "Nie udało się otworzyć okna powiadomień. Uruchom ponownie Discorda i spróbuj jeszcze raz.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "Tak teraz wyglądają twoje powiadomienia. Najedź myszą, aby zostało, kliknij, aby otworzyć Discorda.",
        "label.open": "Otwórz w Discordzie",
        "label.close": "Zamknij",
        "label.reply": "Odpowiedz",
        "label.placeholder": "Odpowiedz {name}",
        "label.send": "Wyślij odpowiedź",
        "label.sending": "Wysyłanie…",
        "label.sent": "Odpowiedź wysłana",
        "label.failed": "Nie udało się wysłać. Naciśnij Enter, aby spróbować ponownie.",
        "context.dm": "Wiadomość prywatna",
        "context.group": "Grupowa PW",
        "body.hidden": "Nowa wiadomość",
        "body.attachment": "Wysłał(a) załącznik",
    },
    "pt-BR": {
        "settings.corner": "Canto",
        "settings.corner.description": "Onde as notificações aparecem na sua tela.",
        "corner.bottomRight": "Inferior direito",
        "corner.bottomLeft": "Inferior esquerdo",
        "corner.topRight": "Superior direito",
        "corner.topLeft": "Superior esquerdo",
        "settings.screen": "Tela",
        "settings.screen.description": "Com mais de um monitor, em qual elas aparecem.",
        "screen.discord": "A tela em que o Discord está",
        "screen.primary": "Sua tela principal",
        "screen.cursor": "A tela em que o mouse está",
        "settings.duration": "Segundos na tela",
        "settings.duration.description": "Passar o mouse por cima mantém a notificação.",
        "settings.maxVisible": "No máximo na tela",
        "settings.maxVisible.description": "As mais antigas abrem espaço para as novas.",
        "settings.showText": "Mostrar o texto da mensagem",
        "settings.showText.description": "Desative para mostrar só de quem é, para quando outras pessoas veem sua tela.",
        "settings.reply": "Responder pela notificação",
        "settings.reply.description": "Um botão Responder que envia uma resposta de verdade sem abrir o Discord.",
        "settings.others": "Outras notificações também",
        "settings.others.description": "Pedidos de amizade e tudo mais que o Discord avisa, no mesmo estilo.",
        "settings.overFullscreen": "Mostrar sobre apps em tela cheia",
        "settings.overFullscreen.description": "O Discord segura as notificações durante um jogo em tela cheia ou com o Assistente de foco ligado. Ative para mostrá-las mesmo assim.",
        "panel.test": "Mostrar uma notificação de teste",
        "panel.testFailed": "Não foi possível abrir a janela de notificações. Reinicie o Discord e tente de novo.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "É assim que suas notificações ficam agora. Passe o mouse para mantê-la, clique para abrir o Discord.",
        "label.open": "Abrir no Discord",
        "label.close": "Fechar",
        "label.reply": "Responder",
        "label.placeholder": "Responder a {name}",
        "label.send": "Enviar resposta",
        "label.sending": "Enviando…",
        "label.sent": "Resposta enviada",
        "label.failed": "Não foi possível enviar. Pressione Enter para tentar de novo.",
        "context.dm": "Mensagem direta",
        "context.group": "DM em grupo",
        "body.hidden": "Nova mensagem",
        "body.attachment": "Enviou um anexo",
    },
    ru: {
        "settings.corner": "Угол",
        "settings.corner.description": "Где на экране появляются уведомления.",
        "corner.bottomRight": "Справа внизу",
        "corner.bottomLeft": "Слева внизу",
        "corner.topRight": "Справа вверху",
        "corner.topLeft": "Слева вверху",
        "settings.screen": "Экран",
        "settings.screen.description": "Если мониторов несколько — на каком они появляются.",
        "screen.discord": "Экран, где открыт Discord",
        "screen.primary": "Основной экран",
        "screen.cursor": "Экран, где мышь",
        "settings.duration": "Секунд на экране",
        "settings.duration.description": "Пока на уведомление наведена мышь, оно не исчезает.",
        "settings.maxVisible": "Не больше на экране",
        "settings.maxVisible.description": "Старые уступают место новым.",
        "settings.showText": "Показывать текст сообщения",
        "settings.showText.description": "Выключите, чтобы видеть только отправителя, если ваш экран видят другие.",
        "settings.reply": "Ответ из уведомления",
        "settings.reply.description": "Кнопка «Ответить», которая отправляет настоящий ответ, не открывая Discord.",
        "settings.others": "И другие уведомления",
        "settings.others.description": "Запросы в друзья и всё остальное, о чём сообщает Discord, в том же стиле.",
        "settings.overFullscreen": "Показывать поверх полноэкранных приложений",
        "settings.overFullscreen.description": "Discord придерживает уведомления, пока открыта полноэкранная игра или включена фокусировка внимания. Включите, чтобы всё равно их показывать.",
        "panel.test": "Показать тестовое уведомление",
        "panel.testFailed": "Не удалось открыть окно уведомлений. Перезапустите Discord и попробуйте снова.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "Так теперь выглядят ваши уведомления. Наведите мышь, чтобы оно осталось, нажмите, чтобы открыть Discord.",
        "label.open": "Открыть в Discord",
        "label.close": "Закрыть",
        "label.reply": "Ответить",
        "label.placeholder": "Ответить {name}",
        "label.send": "Отправить ответ",
        "label.sending": "Отправка…",
        "label.sent": "Ответ отправлен",
        "label.failed": "Не удалось отправить. Нажмите Enter, чтобы повторить.",
        "context.dm": "Личное сообщение",
        "context.group": "Групповой чат",
        "body.hidden": "Новое сообщение",
        "body.attachment": "Отправил(а) вложение",
    },
    tr: {
        "settings.corner": "Köşe",
        "settings.corner.description": "Bildirimlerin ekranında nerede çıkacağı.",
        "corner.bottomRight": "Sağ alt",
        "corner.bottomLeft": "Sol alt",
        "corner.topRight": "Sağ üst",
        "corner.topLeft": "Sol üst",
        "settings.screen": "Ekran",
        "settings.screen.description": "Birden fazla monitörde, hangisinde çıkacakları.",
        "screen.discord": "Discord'un olduğu ekran",
        "screen.primary": "Ana ekranın",
        "screen.cursor": "Farenin olduğu ekran",
        "settings.duration": "Ekranda kalma süresi (saniye)",
        "settings.duration.description": "Farenle üzerine gelince bildirim kaybolmaz.",
        "settings.maxVisible": "Ekranda en fazla",
        "settings.maxVisible.description": "Eskiler yenilere yer açar.",
        "settings.showText": "Mesaj metnini göster",
        "settings.showText.description": "Kapatırsan yalnızca kimden geldiği görünür; ekranını başkaları görebiliyorsa işe yarar.",
        "settings.reply": "Bildirimden yanıtla",
        "settings.reply.description": "Discord'u açmadan gerçek bir yanıt gönderen bir Yanıtla düğmesi.",
        "settings.others": "Diğer bildirimler de",
        "settings.others.description": "Arkadaşlık istekleri ve Discord'un sana bildirdiği her şey, aynı tarzda.",
        "settings.overFullscreen": "Tam ekran uygulamaların üstünde göster",
        "settings.overFullscreen.description": "Tam ekran bir oyun veya Odak yardımı açıkken Discord bildirimleri bekletir. Yine de göstermek için bunu aç.",
        "panel.test": "Deneme bildirimi göster",
        "panel.testFailed": "Bildirim penceresi açılamadı. Discord'u yeniden başlatıp tekrar dene.",
        "test.title": "Evi",
        "test.context": "Pretty Notifications",
        "test.body": "Bildirimlerin artık böyle görünüyor. Ekranda tutmak için farenle üzerine gel, Discord'u açmak için tıkla.",
        "label.open": "Discord'da aç",
        "label.close": "Kapat",
        "label.reply": "Yanıtla",
        "label.placeholder": "{name} adlı kişiyi yanıtla",
        "label.send": "Yanıtı gönder",
        "label.sending": "Gönderiliyor…",
        "label.sent": "Yanıt gönderildi",
        "label.failed": "Gönderilemedi. Tekrar denemek için Enter'a bas.",
        "context.dm": "Direkt mesaj",
        "context.group": "Grup DM",
        "body.hidden": "Yeni mesaj",
        "body.attachment": "Bir dosya gönderdi",
    },
});
